language: node_js
node_js:
  - node
  - lts/*
script:
  - npm run lint
  - npm test
  - npm run docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB
  keep_history: true
  target_branch: gh-pages
  local_dir: "./docs/snooful"
  repo: "Snooful/Docs"
  on:
    branch: master
